[workspace]
members = [
    "programs/brain",
    "programs/guardian",
    "programs/agent-syndicate",
    "programs/fee-collector",
]
resolver = "2"

[profile.release]
overflow-checks = false
lto = true
codegen-units = 1

[profile.release-with-logs]
inherits = "release"
debug = true
