[package]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
spl-token = { version = "4", features = ["no-entrypoint"] }
solana-program = "1.18"
thiserror = "1"

[lib]
crate-type = ["cdylib", "lib"]
